app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

/*Route::get('/', function () {
    return view('welcome');
});*/

/*Route::get('/', function () {
    return view('master');
});*/


Route::get('/', 'TaskController@index');
 
Route::resource('tasks', 'TaskController');

app/Task.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Task extends Model
{
    //
    public $fillable = ['name', 'description'];
}

app/User.php
<?php

namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesResources;

class Controller extends BaseController
{
    use AuthorizesRequests, AuthorizesResources, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/TaskController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests;
use App\Task;

class TaskController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        //
      $tasks = Task::orderBy('name','ASC')->paginate(5);
      return view('task.list',compact('tasks'))->with('i', ($request->input('page', 1) - 1) * 5);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('task.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // validated input request
        $this->validate($request, [
            'name' => 'required|max:255',
            'description' => 'required'
        ]);
 
        // create new task
        Task::create($request->all());
        return redirect()->route('tasks.index')->with('success', 'Your task has been added successfully!');
    }
 

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        // show selected task
        $task = Task::find($id);
        return view('task.show',compact('task'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //edit selected task
        $task = Task::find($id);
        return view('task.edit', compact('task'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //Update current task
        $this->validate($request, [
            'name' => 'required',
            'description' => 'required'
        ]);
        Task::find($id)->update($request->all());
        return redirect()->route('tasks.index')->with('success','Task has been updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //Deleting a task
    Task::find($id)->delete();
        return redirect()->route('tasks.index')->with('success','Task has been removed successfully');
    }
}

resources/views/master.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>My Task List</title>
 
    <!-- Bootstrap CSS File  -->
     <!--<link rel="stylesheet" type="text/css" href="{{ URL::asset('bootstrap/css/bootstrap.min.css') }}"/> -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha/css/bootstrap.css" rel="stylesheet">
</head>
<body>
 
<div class="container">
 
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="">Task List CRUD Application</a>
            </div>
            <ul class="nav navbar-nav">
 
            </ul>
        </div>
    </nav>
 
    <head>
        <h1></h1>
    </head>
 
    @yield('content')
 
</div>
</body>
</html>

resources/views/task/create.blade.php
@extends('master')
 
@section('content')
 
    <div class="panel panel-default">
        <div class="panel-heading">Add New Task</div>
        <div class="panel-body">
 
            @if (count($errors) > 0)
                <div class="alert alert-danger">
                    <strong>Errors:</strong>
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
 
            {{ Form::open(array('route' => 'tasks.store','method'=>'POST')) }}
            <div class="form-group">
                <label for="name">Task Name</label>
                <input type="text" name="name" class="form-control" value="{{  old('name') }}">
            </div>
            <div class="form-group">
                <label for="description">Task Description</label>
                <textarea name="description" class="form-control" rows="3">{{  old('description') }}</textarea>
            </div>
            <div class="form-group">
                <input type="submit" value="Add New Task" class="btn btn-info">
                <a href="{{ route('tasks.index') }}" class="btn btn-primary">Cancel</a>
            </div>
            {{ Form::close() }}
        </div>
    </div>
 
@endsection

resources/views/task/edit.blade.php
@extends('master')
 
@section('content')
 
    <div class="panel panel-default">
        <div class="panel-heading">Edit Task</div>
        <div class="panel-body">
 
            @if (count($errors) > 0)
                <div class="alert alert-danger">
                    <strong>Errors:</strong>
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
 
            {!! Form::model($task, ['method' => 'PATCH','route' => ['tasks.update', $task->id]]) !!}
            <br/>
            <div class="form-group">
                <label for="name">Task Name</label>
                <input type="text" name="name" class="form-control" value="{{  $task->name }}">
            </div>
            <div class="form-group">
                <label for="description">Task Description</label>
                <textarea name="description" class="form-control" rows="3">{{  $task->description }}</textarea>
            </div>
            <div class="form-group">
                <input type="submit" value="Save New Changes" class="btn btn-info">
                <a href="{{ route('tasks.index')  }}" class="btn btn-info">Cancel</a>
            </div>
            {!! Form::close() !!}
        </div>
    </div>
 
@endsection

resources/views/task/list.blade.php
@extends('master')
 
@section('content')
 
    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif
 
    <div class="panel panel-default">
        <div class="panel-heading">
            Task List
        </div>
        <div class="panel-body">
            <div class="form-group">
                <div class="pull-right">
                    <a href="/tasks/create" class="btn btn-info">Add New Task</a>
                </div>
            </div>
 
            <table class="table table-bordered table-stripped">
                <tr>
                    <th width="20">No</th>
                    <th>Title</th>
                    <th>Description</th>
                    <th width="300">Action</th>
                </tr>
                @if (count($tasks) > 0)
                    @foreach ($tasks as $key => $task)
                        <tr>
                            <td>{{ ++$i }}</td>
                            <td>{{ $task->name }}</td>
                            <td>{{ $task->description }}</td>
                            <td>
                                <a class="btn btn-success" href="{{ route('tasks.show',$task->id) }}">Show</a>
                                <a class="btn btn-primary" href="{{ route('tasks.edit',$task->id) }}">Edit</a>
                                {{ Form::open(['method' => 'DELETE','route' => ['tasks.destroy', $task->id],'style'=>'display:inline']) }}
                                {{ Form::submit('Delete', ['class' => 'btn btn-danger']) }}
                                {{ Form::close() }}
                            </td>
                        </tr>
                    @endforeach
                @else
                    <tr>
                        <td colspan="4">Tasks not found!</td>
                    </tr>
                @endif
            </table>
 
            {{ $tasks->render() }}
 
        </div>
    </div>
 
@endsection

resources/views/task/show.blade.php
@extends('master')
 
@section('content')
 
    <div class="panel panel-default">
        <div class="panel-heading">
            View Task
        </div>
        <br/>
        <div class="panel-body">
            <div class="pull-right">
                <a class="btn btn-info" href="{{ route('tasks.index')  }}">Back</a>
            </div>
            <div class="form-group">
                <strong>Task Name: </strong> {{ $task->name  }}
            </div>
            <div class="form-group">
                <strong>Task Description: </strong> {{ $task->description  }}
            </div>
        </div>
    </div>
 
@endsection